# Generated by Django 3.2.3 on 2021-05-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210524_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Product', 'Product')], default='Blog', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Product', 'Product')], default='Blog', max_length=80),
        ),
    ]
