# Generated by Django 3.2.3 on 2021-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210524_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Product', 'Product')], default='Product', max_length=80),
        ),
    ]
