# Generated by Django 3.2.3 on 2021-05-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210524_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Image'),
        ),
    ]
