# Generated by Django 3.2.3 on 2021-05-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
