# Generated by Django 3.2.3 on 2021-05-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Image'),
        ),
    ]
