# Generated by Django 3.2.3 on 2021-05-24 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_auto_20210524_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
        migrations.AlterField(
            model_name='showcaser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Following'),
        ),
    ]
