# Generated by Django 3.2.3 on 2021-05-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210524_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaser',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
