# Generated by Django 3.2.3 on 2021-05-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_showcaser_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaser',
            name='bio',
            field=models.CharField(blank=True, max_length=800, verbose_name='Bio'),
        ),
    ]
