# Generated by Django 3.2.3 on 2021-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_showcaser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaser',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
